### ISSUE TITLE
Feature Request: Import SSL Certificate for proxy use.

### ISSUE THREAD

**Issue by JosieBigler** [httptoolkit/mockttp#108]
would it be possible to import an already created SSL cert for the proxy server to use? Rather than importing a CA / Key and then signing / creating a Cert? 

I would be very willing to implement the feature.   But might need some general guidance on how to go about that.  I can see where the `defaultCert` is generated. And it looks like it's only used when `SNI` is not used, otherwise it looks like the cert is dynamically created.

**Comment by JosieBigler** [comment]
Well, very specifically.  Being able to change some of the characteristics of the Cert created might be enough.  Most importantly `organizationName`.   Which is currently defaulting to `Mockttp Cert - DO NOT TRUST'`.   

My initial thoughts were maybe just supplying our own cert might be easier? 

But as I'm writing this, being able to pass a `defaultOrganizationName` (along with the other cert values)  might be easier. 

Our specific case is in the non-SNI case.

**Comment by pimterry** [comment]
Ah, I see ok. Yes, for that case I definitely think being able to configure the default generated certificate settings makes more sense. A PR for that would be very welcome!

I think just adding an `organizationName` parameter to the `https` options (i.e. within our new [BaseCAOptions](https://github.com/httptoolkit/mockttp/blob/432fcc0a57caa3c5cc8b7ef1ff4b05078abe0196/src/util/tls.ts#L21-L26) type) and then using that in the `CA` class during certificate generation should work nicely. You're welcome to add other options there too if there's anything else in certificate generation that you'd find it useful to generate differently.

**Comment by skilbjo** [comment]
hi, follow up question here.

is it possible to generate certificates via LetsEncrypt's `certbot` and then use them in `mockttp` to serve HTTPS properly ?

**Comment by skilbjo** [comment]
@pimterry cc

**Comment by pimterry** [comment]
Hi @skilbjo - yes, you can use certificates from certbot (or from anywhere) with Mockttp, that's no problem. You just need to call [getLocal](https://httptoolkit.github.io/mockttp/functions/getLocal.html) and pass the key & cert (or the path to them) within the `https` option there.
