### ISSUE TITLE
Error will be reported if only one api rule is set

### ISSUE THREAD

**Issue by name-q** [httptoolkit/mockttp#111]
#report errors：
There are no rules configured.
You can fix this by adding a rule to match this request, for example:
mockServer.forGet("/components/overview-cn").thenReply(200, "your response");

#I tried：
await server.forAnyRequest().thenPassThrough()
#This will make the error disappear, but the above rule will be invalid

**Comment by pimterry** [comment]
I think you probably want this:

```javascript
(async () => {
  const mockttp = require('mockttp');
  const https = await mockttp.generateCACertificate();
  const server = mockttp.getLocal({ https });

  await server.forGet('/doc/getAvatarList')
    .thenReply(200, 'demo');

  await server.forUnmatchedRequest().thenPassThrough();

  await server.start();
})();
```

Alternatively, you could put `.always()` after `.forGet('/doc/getAvatarList')` to force it to _always_ apply.

**Comment by name-q** [comment]
> ```js
> await server.forUnmatchedRequest().thenPassThrough();
> ```

await server.forUnmatchedRequest().thenPassThrough();
It solved my problem perfectly 
Fucking great
