### ISSUE TITLE
Using `proxyConfig` with `thenPassThrough()` sends CONNECT to 80 port

### ISSUE THREAD

**Issue by ashishmadeti** [httptoolkit/mockttp#127]
I am using the following code snippet
```js
const mockttp = require('mockttp');

(async () => {

    // Create a proxy server with a self-signed HTTPS CA certificate:
    const https = await mockttp.generateCACertificate();
    const server = mockttp.getLocal({
        https,
        debug: true,
        http2: true
    });

    server.forAnyRequest().thenPassThrough({
        proxyConfig: (obj) => {
            console.log('obj', obj);
            return {
                noProxy: [
                    'localhost', '127.0.0.1', 'local.home'
                ],
                proxyUrl: 'http://150.50.100.10:2222'  // Using a fake URL here, but actual proxy server in practice (squid 3 proxy server)
            }
        },
        beforeResponse: (res) => {
            console.log(res.statusCode)
            // console.log('res.body', res.body.buffer.toString())
            return res
        }
    })
    await server.start(8125);

    // Print out the server details:
    const caFingerprint = mockttp.generateSPKIFingerprint(https.cert)
    console.log(`Server running on port ${server.port}`);
    console.log(`CA cert fingerprint ${caFingerprint}`);
})();
```

I am then using http://localhost:8125 as a proxy server.
When I use it for an https request, it works perfect but when I use it for an http request, the squid proxy (http://150.50.100.10:2222) returns 403. Presumably, because mockttp is trying to send CONNECT request to 80 port of the original host.

Here are the squid proxy logs (1st line is https and second is http):
```
1672856607.180   1077 1XX.XX.1XX.XX TCP_TUNNEL/200 6578 CONNECT api.ipify.org:443 - HIER_DIRECT/XX.XXX.2XX.1XX -
1672856621.261      0 1XX.XX.1XX.XX TCP_DENIED/403 3780 CONNECT api.ipify.org:80 - HIER_NONE/- text/html
``` 

I am using mockttp version `3.6.2`.

Let me know if you need any more information.

**Comment by pimterry** [comment]
Thanks for reporting this @ashishmadeti.

HTTP Toolkit will indeed use CONNECT for all proxying, but in general that's correct! That should work fine. It's just as valid to CONNECT for port 80 as for port 443, and setting up the tunnel with the proxy is totally independent from whether HTTP or HTTPS (or some other protocol) is used within the tunnel afterwards.

I think this is really a Squid configuration issue, and you should configure Squid to allow tunnels on ports other than 443. https://stackoverflow.com/a/31831631/68051 suggests that Squid blocks this by default to enforce encrypted connections, but if you're trying to proxy plain HTTP then you should relax that. Is there a reason that allowing CONNECT on port 80 doesn't work for you?

**Comment by ashishmadeti** [comment]
@pimterry Thank you very much for taking the time out to point my mistake.
I did not know that:
1. CONNECT to 80 is valid
2. My (default) Squid proxy configuration did not allow CONNECT to non SSL ports

For posterity: I have resolved my issue by commenting the following line in default squid proxy configuration
`http_access deny CONNECT !SSL_ports`

PS: Thanks for this awesome project.
