### ISSUE TITLE
[Question] Is there an ability to turn off request buffering? 

### ISSUE THREAD

**Issue by JosieBigler** [httptoolkit/mockttp#129]
I am receiving large files from a client that end up getting terminated, and by best guess is the heap in node get too large and the connection gets aborted. 

My setup is fairly simple at the moment, 

```
    server.forAnyRequest()
    .thenForwardTo("www.url.com")
```

I've tried increasing the max buffer size of node with the following command `node --max-old-space-size=4096 .\server.js` But that resulted in the same problem. 

Just for context, the specific error I get is, 

```
Error: Aborted
    at IncomingMessage.<anonymous> ({path}/node_modules/mockttp/dist/util/buffer-utils.js:63:40)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
    at abortIncoming (node:_http_server:744:9)
    at socketOnClose (node:_http_server:738:3)
    at TLSSocket.emit (node:events:525:35)
    at node:net:317:12
```

**Comment by pimterry** [comment]
Hmmm, it's hard to know. Is it possible to share a full example to reproduce this issue?

While there is some buffering within Mockttp used to expose data for events, that's strictly limited in size. There shouldn't typically be significant buffering for the data as it streams from client to upstream server, it's just piped directly (up to a point - of course if the client is sending data much faster than the server can accept it, eventually there will have to be buffering somewhere).

That error message simply means that the request stream itself has been aborted, which usually means that for some reason the client has disconnected (or been disconnected by the server - e.g. for sending unparseable data). Normally this isn't what I'd expect for memory issues, that would usually have a more explicit "process out of memory" or "can't allocate buffer" kind of error.

If you set a `NODE_DEBUG=http` env var, then node will log info about its low-level HTTP interactions, which may have some clues. It would also be interesting to look at the actual process memory usage, and see if it really is getting close to the 4GB memory limit before it crashes.

**Comment by JosieBigler** [comment]
Through some testing and debugging, I think we've nailed down our error is because of a fussy client, and not because of Mockttp. 

Thank you for the reply!
