### ISSUE TITLE
will mockttp works with openAPI requests 

### ISSUE THREAD

**Issue by ashajoy** [httptoolkit/mockttp#134]
I am trying to mock requests that goes to an openAPI 
I set up everything but my backend is never communication with the mockserver 
I can see the mocker request fire but the mockserver never handles the request

**Comment by pimterry** [comment]
Hi @ashajoy. Mockttp can intercept any HTTP client, the only requirement is that you configure your client to use Mockttp as your HTTP proxy (or to use its address as the server itself, and send requests directly). Are you doing that?

If you're having issues, it would be very helpful if you could share more details of exactly how your complete setup works, what you're trying to do, and what behaviour you're seeing so far.

**Comment by ashajoy** [comment]
Thanks @pimterry It did work now with my openAPI client.My issue was related to a objc_initializeAfterForkError and when I added OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES to my server side env it worked .I will close the issue
