### ISSUE TITLE
Passthrough modifications overrode the body and the content-length header with mismatched values

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/mockttp#146]
Hey Team, below is the code snipped I am trying to run
```
await server.forAnyRequest().forHostname("api.myip.com").thenPassThrough({
        proxyConfig: {
            proxyUrl: proxyURL
        },
        ignoreHostHttpsErrors: true,
        transformRequest: {
            updateHeaders: {
                'x-device-id': androidId
            }
        },
        beforeResponse: async (resp) => {
            const body = await resp.body.getJson();
            const token = body.token;

            if (token) {
                console.log('Token: ' + token);
            }

            return resp;
        }
    });
```

I am getting the error "Passthrough modifications overrode the body and the content-length header with mismatched values"

Is there any way to resolve it?

**Comment by pimterry** [comment]
@vikasg603 the short answer is that you can remove the `return resp` line entirely, and then it'll do what you want.

The long answer:

The value you return from beforeResponse defines what you want to _override_ in the response. If you don't want to modify the response at all, you don't need to return anything.

In this case, you're returning the entire response. Mockttp tries to handle this neatly, e.g. so you can mutate the response and then return it, but it needs to re-evaluate a few parts in case they were modified.

In this case, you're effectively returning a body and headers, and the headers must contain a content-length which doesn't match the length of the body for some reason. Unless you're testing intentionally broken responses, you probably don't want to do that.

It's a bit surprising that this would happen when you're returning a response unmodified. There's all sorts of interesting cases that could cause this, but in this case, I suspect it's most likely that there's a content-encoding header (i.e. the body is compressed) and a fixed content-length set. In that case, I think Mockttp will automatically re-encode the body for you (compressing it from scratch) but doesn't know exactly what level of compression was used originally, so it ends up with a different length, and so you see this error.

If you want to avoid this in general, you need to make sure you return just the data you want to override. Mockttp will automatically handle anything you don't override correctly (e.g. if you don't override the headers, it'll update the content-length automatically even if you change the body length).

**Comment by vikasg603** [comment]
Hey, @pimterry thanks for the response.
I misinterpreted the meaning of: "All fields on the object are optional, and returning undefined is equivalent to returning an empty object (transforming nothing)."

 I thought it would return an undefined response, but thanks for the great explanation.
