### ISSUE TITLE
request object on beforeResponse hook

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/mockttp#147]
Hey team, is there any way to find out what was the request when looking for beforeResponse hook?
Currently, I see we get only a response object but I guess adding a conditional response based on the request will be a much better idea

**Comment by pimterry** [comment]
Hi @vikasg603, see https://github.com/httptoolkit/mockttp/issues/80. In summary: right now that's not available, but it's a good idea and PRs to add it are very welcome. I'm going to close this as a duplicate, but discussion over there is very welcome if you're interested in working on this.
