### ISSUE TITLE
Build failures with webpack: Module not found: Error: Can't resolve '_stream_wrap' in 'C:\vscode-extensions\code-responder\node_modules\@httptoolkit\httpolyglot\dist'

### ISSUE THREAD

**Issue by kevinamick** [httptoolkit/mockttp#159]
I'm building a vscode extension that uses mockttp to intercept web requests and when compiling with webpack I receive this error:

```Module not found: Error: Can't resolve '_stream_wrap' in 'C:\vscode-extensions\code-responder\node_modules\@httptoolkit\httpolyglot\dist'```

mockttp version: 3.9.4
Node version: 16.18.0
npm version: 8.19.2
webpack version: 5.89.0

Looks like the package is using stream_wrap for node versions <= 12 but not including the package anymore?

`node_modules\@httptoolkit\httpolyglot\src\index.ts`
Line number 177

```typescript 
// For HTTP/2 we hit issues when passing non-socket streams (like H2 streams for proxying H2-over-H2).
if (NODE_MAJOR_VERSION <= 12) {
      // For Node 12 and older, we need a (later deprecated) stream wrapper:
      const StreamWrapper = require('_stream_wrap');
      socket = new StreamWrapper(socket);
} else {
      // For newer node, we can fix this with a quick patch here:
      const socketWithInternals = socket as { _handle?: { isStreamBase?: boolean } };
      if (socketWithInternals._handle) {
        socketWithInternals._handle.isStreamBase = false;
      }
}
```

**Comment by pimterry** [comment]
Hmm, that's interesting. The `_stream_wrap` here is a red herring - the problem is that httpolyglot is being included in your bundle at all. Httpolyglot is a node low-level networking module, so it should never be used in browsers, and the browser entrypoints in this package should end up importing it in the first place anyway.

Is it possible to share the project code, so I can reproduce this?

Alternatively, can you tweak your webpack config, and work out why httpolyglot is being included in the first place? There' an option that I think should enable this: https://webpack.js.org/configuration/stats/#statsreasons. Or you can enable `stats: 'verbose'` and dig through the huge amount of details it'll give you there. If you can work out the path from your import code to httpolyglot, I can work out where it's gone wrong and look into that.

**Comment by kevinamick** [comment]
Here is the repo: https://github.com/kevinamick/code-responder

Looks like http-combo-server.js imports http-polyglot.

```
ModuleNotFoundError: Module not found: Error: Can't resolve '_stream_wrap' in 'C:\vscode-extensions\code-responder\node_modules\@httptoolkit\httpolyglot\dist'
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\Compilation.js:2022:28
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (C:\vscode-extensions\code-responder\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\vscode-extensions\code-responder\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at C:\vscode-extensions\code-responder\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
 @ ./node_modules/mockttp/dist/server/http-combo-server.js 10:20-55
 @ ./node_modules/mockttp/dist/server/mockttp-server.js 17:28-58
 @ ./node_modules/mockttp/dist/main.js 14:25-59
```

![image](https://github.com/httptoolkit/mockttp/assets/15185225/fca0d91c-0edb-4463-ad2a-4148af17be07)

**Comment by kevinamick** [comment]
vscode extensions run in node context due to vscode running in Electrum which bundles the browser with node. Not sure on the specifics there. But your reference to the httptoolkit-server project pointed me in the right direction and explains the issue. 

The _stream_wrap library is defined as external there, so it's not packaged. Simply adding that lib as external to my project did the trick.

Thanks for your help!
