### ISSUE TITLE
npm audit vulnerability

### ISSUE THREAD

**Issue by kibertoad** [httptoolkit/mockttp#163]
Running `npm audit` on the latest mockttp returns this warning:

```
node_modules/ip
  pac-resolver  >=1.3.0
  Depends on vulnerable versions of ip
  node_modules/pac-resolver
    pac-proxy-agent  >=1.1.0
    Depends on vulnerable versions of pac-resolver
    node_modules/pac-proxy-agent
      mockttp  >=3.4.0
      Depends on vulnerable versions of pac-proxy-agent
      node_modules/mockttp
```

I know this isn't a real problem because mockttp is not run in production, but it generates noise which potentially obscures real problems.

**Comment by kibertoad** [comment]
Thank you! I'll follow up upstream.

**Comment by pimterry** [comment]
I think this is now resolved - both `pac-resolver` and `socks` (internal dependencies within the proxy agent packages) have successfully updated their dependencies to not depend on the affected versions of `ip`, and a fresh Mockttp install has no audit warnings.

If you have an existing install, you'll want to update those dependencies to fix this warning (but it's not an urgent issue - as noted above, there is no possible impact for this issue in any Mockttp usage). I'll close this now as fixed.
