### ISSUE TITLE
How to specify upstream proxy?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/mockttp#165]
Hi,

Just wanted to know if there is anyway to specify upstream http proxy from js code. I think HTTP_PROXY env works, but wanted to know if there are apis to specify it from Typescript code without messing process.env

**Comment by pimterry** [comment]
Do you mean for a Mockttp rule, to define how matching traffic is forwarded, or for normal JS outside Mockttp to tell a normal Node.js process to use a proxy?

Although HTTP_PROXY is a standard, it's actually not supported by Node by default at all, and won't work without use of a specific library that supports it.

**Comment by shirshak55** [comment]
@pimterry 
yes, 

Here is my setup

Chrome -> Mockttp -> Internet

I want 

Chrome -> Mockttp -> Upstream Proxy -> Internet


how do i specify upstream proxy?

**Comment by pimterry** [comment]
Upstream proxies are configured as part of passthrough rules, you pass the config to the rule, and all matching proxies traffic will use that upstream proxy en route. See the docs here: https://httptoolkit.github.io/mockttp/interfaces/requestHandlers.PassThroughHandlerOptions.html#proxyConfig. Lots of examples in the tests here: https://github.com/httptoolkit/mockttp/blob/main/test/integration/proxying/upstream-proxying.spec.ts.

Does that work for you?

**Comment by shirshak55** [comment]
@pimterry 

Thank this is what I wanted.

:)
