### ISSUE TITLE
How to change an intercepted request body variable before forwarding it ?

### ISSUE THREAD

**Issue by mainlyek** [httptoolkit/mockttp#170]
Hello, I'm trying to intercept a request to an url, and change the b parameter before the request is sent.
I have search on google, but all the example I found were for response modification, which is different.
I want to change just the b value here,
a=hh4&b=3gg&c=464
then send the request to the server.
but the headers should be kept as the request is made by a local software which is logged.
thanks

HEADERS
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Content-Length: 552
Content-Type: application/x-www-form-urlencoded
Cookie:__SYS_ID=d39a040181ecee;

server.forAnyRequest().thenPassThrough({
    beforeRequest: async (request) => {
      if (request.path.includes('/user/profile/get-login')) {
        const requestBody = await request.body.getFormData();
        console.log('a:', requestBody.a);
        console.log('b:', requestBody.b);
        console.log('c:', requestBody.c);
      }
    },
    beforeResponse: async (response) => {
      }
    },
  });

**Comment by pimterry** [comment]
Hi @mainlyek. To modify the request body, you just need to return the modification you want to make from the `beforeRequest` function. If you look at the docs for the return type [here](https://httptoolkit.github.io/mockttp/interfaces/requestHandlers.CallbackRequestResult.html) then you'll see the fields you can return.

This doesn't have support for automatically serializing the body for you, but you can do that manually and return a string directly with `{ body: "replacement-body-string" }` to do this.

There's an example (returning a buffer here, but a plain string would work too) in the tests here: https://github.com/httptoolkit/mockttp/blob/3504da01b08064e15cda1c30e5be0111e40a38ca/test/integration/proxying/http-proxying.spec.ts#L487-L507

**Comment by mainlyek** [comment]
thank you for your help made it work :-)
