### ISSUE TITLE
mockttp handles duplicate headers differently from a browser

### ISSUE THREAD

**Issue by kspeers-r7** [httptoolkit/mockttp#176]
When mockttp intercepts a response with duplicate headers in the response, the duplicate headers are combined by mockttp into an array of values - for some headers, this can cause an error. Requests not routed through mockttp are handled correctly by the browser, ie. only the last header value is used.

This was seen on an internal site where the server is returning a duplicate "x-content-type-options" header:
`x-content-type-options:nosniff`
`x-content-type-options:nosniff`

When routed through mockttp, the header is transformed into:
`x-content-type-options:["nosniff","nosniff"]`
which is rejected by Chrome with an error:
`Failed to handle request: Header field "x-content-type-options" must only have a single value`

When loaded directly in Chrome, the site loads correctly

Apologies that I don't have a reproducible test case for this issue.
I realise that for this header, the correct solution is to just send the header once, but the issue will apply to other headers

**Comment by pimterry** [comment]
Even without a test case, can you share the specific rule that's handling this traffic at least?

For a vanilla passthrough rule without configuration, I'm fairly sure the headers are proxied _exactly_ as received (and there are [tests](https://github.com/httptoolkit/mockttp/blob/7b32a626c0c66c704eb58b61a4e2ae7d9e3c63eb/test/integration/proxying/http-proxying.spec.ts#L102-L140) specifically covering this case already). I know though that there a few more specific cases where configuration can result in headers not being proxied entirely transparently (some API usages and types of traffic can require mockttp to translate headers at various points, losing the original formatting) so presumably you're running into one of those cases. Unfortunately it's hard to be more specific without seeing the actual code that's causing this though.

**Comment by pimterry** [comment]
Oh, and a caveat here: although this behaviour isn't technically what I'd like Mockttp to do, it is broadly correct HTTP behaviour. From [the RFC 3.2.2](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2):

> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma

That's allowed because:

> A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list

Which I think means the server is definitely wrong, and for a proxy or recipient, `x-content-type-options: nosniff` x2 should be equivalent to `x-content-type-options: nosniff, nosniff` by any correct implementation. So in this case, it should really be treated as invalid by Chrome in _both_ cases (of course reality is different & imperfect, and so Mockttp does its best to avoid any modifications of headers regardless, but the context is interesting).

**Comment by kspeers-r7** [comment]
I had also read RFC 3.2.2 and agree that `x-content-type-options: nosniff, nosniff` is correct according to the RFC, but what I see is `x-content-type-options:["nosniff","nosniff"]` (which is wrong).

Interestingly, other headers such as `cache-control`, `set-cookie` and `x-test` are handled correctly - from the RFC, `set-cookie` is definitely an exception but the other two are not combined by mockttp.

In my mockttp, I'm using `handleBeforeResponse` and just reading the `headers` to handle specific mimetypes differently, but for HTML (where I just check the content-type header), I still get `x-content-type-options:["nosniff","nosniff"]` if the `x-content-type-options:nosniff` was set twice by the server

**Comment by pimterry** [comment]
> I had also read RFC 3.2.2 and agree that x-content-type-options: nosniff, nosniff is correct according to the RFC, but what I see is x-content-type-options:["nosniff","nosniff"] (which is to me and the browser is wrong).

Ah yes, that definitely sounds incorrect.

Can you share the code you're using to define this rule? As much as possible really - even if it's not a completely runnable standalone repro it will still make the issue much clearer. It's be very hard to debug or investigate this without the specific code that demonstrates the issue.

**Comment by kspeers-r7** [comment]
Sample code:
>   static async handleBeforeResponse(response) {
    const { headers } = response
    const contentTypeHeader = headers['content-type'];
    if (contentTypeHeader.startsWith(type))) {
          // as we are in beforeResponse, we return the response object from _makeResponse
          return getResponseAndTrackBlocked({ blockedBy: BLOCKED_BY.MIME_TYPE, status: STATUS_OK_NO_CONTENT, url })
  }

Sample expressJS code to test:
> app.route('/test/serve/duplicate-headers').
  all((req, res) => { // for all methods
    // note: with expressJS
    //   * calling `res.set` twice, will overwrite any pre-existing value set
    //   * calling `res.cookie` can be set mutiple times, but will overwrite any existing cookie headers not set by `res.cookie`
    res.set('content-type', 'text/html; charset=utf-8');
    res.set('x-content-type-options', 'nosniff');
    res.append('x-content-type-options', 'nosniff');
    res.set('set-cookie', 'abc=def,ghi=jkl'); // combined cookie in a Set-Cookie header
    res.append('set-cookie', 'mno=pqr'); // additional set-cookie header
    res.set('x-test', '1');
    res.append('x-test', '2');
    res.set('cache-control', 'no-cache');
    res.append('cache-control', 'no-store');
    res.status(200).send("<html><body>hello world</body></html>")
  })

**Comment by pimterry** [comment]
Can you share the full contents of `getResponseAndTrackBlocked`?

What happens here depends significantly on exactly what you return from this function, so I need to be able to fully see what that is to be able to reproduce and debug this.

Right now, I've just done some testing and I can't find any obvious way to make Mockttp return values in the way you're describing. In all my test cases, while some details of raw headers can be lost when returning headers from `beforeResponse` (like casing of header names or some parts of header ordering in certain duplicate cases) I can't find any way to make Mockttp serialize the headers into a string like you've shown above. That means this must be closely linked to the details of exactly how you're using Mockttp, and you're going to need to share all the code related to that (or some other reproducible test case) for us to be able to dig into this any further.

If sharing that is problematic, you're welcome to take an existing Mockttp test like [this one](https://github.com/httptoolkit/mockttp/blob/7b32a626c0c66c704eb58b61a4e2ae7d9e3c63eb/test/integration/proxying/http-proxying.spec.ts#L755-L779) and modify it until it fails in the same way that you're seeing in your codebase.

You can run the tests by just cloning the repo then running `npm install` and `npm test`. After the first run, just running `npm run test:node` will rerun the tests without rebuilding the non-test code, and you can use `.only` to run just specific individual test cases (i.e. modify `it('...'` to `it.only('...'`) so you can quickly iterate on those.

**Comment by kspeers-r7** [comment]
once again, thanks for the quick response - I'm in the UK but will have a chance to experiment more tomorrow. In this case, for my test page and the internal site, the `getResponseAndTrackBlocked` isn't being called. I've just rerun my test page and it DOES work correctly - only the internal site is failing. This may be a false alarm - either way, I'll either confirm the false alarm or provide you with more info.

**Comment by kspeers-r7** [comment]
I was able to reproduce it with a public site - is there a way I can send you the site URL privately?
my email address is keith_speers@rapid7.com if that works for you

**Comment by pimterry** [comment]
Thanks, I've sent you an email

**Comment by kspeers-r7** [comment]
Many thanks for the CURL command which makes it easy to confirm the rawHeaders are correct. Using standalone test code, and checking the response.rawHeaders, I was able to see it working so I'll close this issue out.
