### ISSUE TITLE
Listen on `0.0.0.0` instead of just `localhost`?

### ISSUE THREAD

**Issue by skilbjo** [httptoolkit/mockttp#182]
hi, question is in the title. is it possible?

seems like though you may have intentionally designed the lib to listen only on `localhost` ?

https://github.com/httptoolkit/mockttp/blob/main/src/server/mockttp-server.ts#L215

**Comment by skilbjo** [comment]
@pimterry can you confirm that? (please see below for why I ask)

is the server listening on host `0.0.0.0` in the `httptoolkit/mockttp` codebase, or the `httptoolkit/httpolyglot` codebase? i did a search of the codebase for `0.0.0.0` and got no hits, meanwhile i get hits of `127.0.0.1` and `localhost` on both codebases, so hoping you can clarify.

```
@Johns-MacBook-Air:proxy-mode $ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> const server = require("mockttp").getLocal()
undefined
> await server.start()
undefined
> server.url
'http://localhost:8000'
```

**Comment by pimterry** [comment]
Yes, it's listening on 0.0.0.0. See the explanation of server.url in my previous message.

If you want to know what addresses mockttp or any other process is listening on, check netstat for the full details.
