### ISSUE TITLE
Jest detects 1 open handle after test run

### ISSUE THREAD

**Issue by roberttaylor426** [httptoolkit/mockttp#31]
We're using Mockttp with Jest, with the `--detectOpenHandles` option set, and after our tests  complete we're seeing the following warning:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
  ●  Timeout
      at Object.<anonymous> (node_modules/mockttp/src/util/socket-util.ts:68:5)
```

Taking a look at [the code in question](https://github.com/httptoolkit/mockttp/blob/master/src/util/socket-util.ts#L68) it seems clear why this is happening, but is there a suggested workaround? We'd rather avoid the false-negative.

Happy to raise a PR if needed.

**Comment by roberttaylor426** [comment]
Thanks for the quick response and the various suggestions. The tests do indeed exit successfully, it's just an undesirable warning message displaying at the end of the test run.

I take your point about the `.unref()`; I'll have a closer look at what Jest is doing and try to better understand their intent. As you say, it might be something that could be fixed / refined on their side.

**Comment by pimterry** [comment]
I did some testing and I'm confident this is both a Jest bug, and an easy to fix bug (for Node 11+ at least).

I've filed an issue over there to get that sorted: https://github.com/facebook/jest/issues/8939. I'll leave this open until that's resolved though.

**Comment by roberttaylor426** [comment]
You beat me to it :-) 

Thanks!

**Comment by pimterry** [comment]
That Jest PR still hasn't been released yet, but Mockttp conveniently no longer uses that setInterval (as of 0.18.0), so I'm going to close this regardless. Thanks for the report!

**Comment by roberttaylor426** [comment]
Thanks very much for your help!
