### ISSUE TITLE
Run mockttp in Angular runtime - ng serve

### ISSUE THREAD

**Issue by hetdev** [httptoolkit/mockttp#33]
Hi
When I try to run mockttp from a angular component i get the following error
anyone know how to fixed?
```
ERROR in ./node_modules/brotli/dec/dictionary-browser.js
Module not found: Error: Can't resolve 'fs' in 'C:\SEON\media-management-ui\node_modules\brotli\dec'
ERROR in ./node_modules/mockttp/dist/util/socket-util.js
Module not found: Error: Can't resolve 'net' in 'C:\SEON\media-management-ui\node_modules\mockttp\dist\util'
```

**Comment by hetdev** [comment]
Hi @pimterry 
I'm using the angularCli for the project

**Comment by pimterry** [comment]
Ok. Angular CLI is using webpack internally, and you'll need to configure that to make this work.

You can customize the webpack config that angular CLI uses by following the instructions in https://alligator.io/angular/custom-webpack-config/. In your case, you just need to merge the config I've shown above, e.g.

```js
module.exports = {
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
```

**Comment by hetdev** [comment]
After the setup, no compile errors, but when you call the `mockServer.start()` the browser console shows:
```
ERROR Error: Uncaught (in promise): TypeError: Network request failed
TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror]
```

**Comment by pimterry** [comment]
Are you running a standalone server? Take a look at the [browser setup docs](https://github.com/httptoolkit/mockttp/blob/master/docs/setup.md#browser-setup) for the full instructions.

In short: Mockttp uses a real HTTP server. You can't start an HTTP server inside a browser, but you do want your test code to run inside the browser. To do so, you need to start a 'standalone' server outside the browser (which does nothing by itself, but can be controlled by the browser). Once that's running, you can call `getLocal` inside the browser and it'll automatically use it.

**Comment by hetdev** [comment]
no sir, im running the getLocal()
```

  server;

  ngOnInit() {
    this.server = mockhttp.getStandalone();
    this.start();
    
  }

  public async start  () {
    await this.server.start();
  }
```

**Comment by hetdev** [comment]
I'm using jest framework for the test, and the work fine as expected, but i'm trying to running in develop as after i run the `ng server` command

**Comment by pimterry** [comment]
I'm not really sure what you mean, sorry @hetdev. In general though, you just need to:

* Start a standalone server (for example using `mockttp -c <your server command>`)
* While that's running:
  * Require mockttp, and use `getLocal` to start & configure a server
  * Make some HTTP requests that go to the server (either use it as a proxy, or make requests to `mockServer.url` directly).

Does that help? If you can share a full example and the steps you're running that aren't working, I'd be happy to take a closer look.

**Comment by pimterry** [comment]
@hetdev have you tried running this with `mockttp -c ng serve`?
