### ISSUE TITLE
Integrating with Cypress

### ISSUE THREAD

**Issue by mvasin** [httptoolkit/mockttp#35]
This question is mostly about Cypress, so if you feel it's totally irrelevant - feel free to close. If you can help - that would be great!

I have backend-for-frontend that does SSR (and all the necessary requests to the upstream backends in the course of it). Cypress can mock requests, but only those that leave browser, and that's not helpful in my case. I'm interested in mocking the requests that leave BFF, towards upstream backends.

I found a relevant SO thread https://stackoverflow.com/questions/47631821/ but it still doesn't completely click for me how to practically integrate Mockttp and Cypress. A small example would be very helpful.

**Comment by pimterry** [comment]
Hi @mvasin - not irrelevant at all, but I don't know Cypress well myself, so I don't have any immediate answers. Good question anyway - Mockttp can certainly do what you're looking for, and I'm happy to help set it up, I'm sure others will be in the same spot anyway.

The general flow for using Mockttp is:

1. Start the server. Sounds like your tests are orchestrated from node, so that's just:
  ```ts
  const server = getLocal();
  await server.start();
  ```
2. Mock the requests you'd like to handle:
  ```ts
  // Match direct requests with a given response
  server.get('/').thenReply(200, "mock response");
  // Match proxied requests, add more complex filters & responses:
  server.get('http://example.com/')
    .withJsonBodyIncluding({ action: 'create' })
    .thenJson(202, { id: 123 });
  // Match wildcards for more control:
  server.get(/.*.html/).thenCallback((request) => {
    return { statusCode: 200 };
  });
  server.anyRequest().thenPassThrough(); // Proxy requests to real servers
  ```
  * There's a lot of options here, see [the MockRuleBuilder docs](https://httptoolkit.github.io/mockttp/classes/_rules_mock_rule_builder_.mockrulebuilder.html) for the full list, or take a look through the [matchers](https://github.com/httptoolkit/mockttp/tree/master/test/integration/matchers) and [handlers](https://github.com/httptoolkit/mockttp/blob/master/test/integration/handlers.spec.ts) tests for some examples.
3. Send your HTTP traffic to your Mockttp server (`server.url`).
  * That means either configure your application to send traffic directly to mockttp or configure your app to use mockttp as a proxy.
  * Which to use depends on your app - configuring the URL is generally simpler, but not always possible, whilst almost all HTTP clients will have a way to globally configure an HTTP proxy to use.
  * If you want to mock HTTPS traffic, you'll also need to generate and trust a CA certificate.
  * There's more detail on this here: https://github.com/httptoolkit/mockttp/blob/master/docs/setup.md
4. Run your test.
  * `thenX()` returns a rule instance that you can use for mock verification, if you'd like.
5. Stop the server when you're done: `await server.stop()`.

Does that help? Let me know if you've got specific questions or if any of the above doesn't make sense.

**Comment by mvasin** [comment]
Thank you for the elaborate answer, Tim!

> Sounds like your tests are orchestrated from node

Do you mean the `it(...)` code? AFAIK it's not the case for Cypress - the test code runs in the browser, but the browser API also has `cy.exec` and `cy.task` commands that allow to execute arbitrary code in the counterpart Node process.

I don't understand how the _mock client_ communicates to the _mock server_, and that's what I need to let Cypress set up the mocked responses in the beginning of each test.

To model the situation, I came up with two files - `server.js` and `client.js`.

server.js:
```
require('mockttp').getStandalone().start()
```

client.js:
```
const mockServer = require('mockttp').getRemote()
const superagent = require('superagent')

mockServer.get("/mocked-path").thenReply(200, "A mocked response")
  .then(() => superagent.get("http://localhost:8080/mocked-path"))
  .then(response => console.log('response.text:', response.text))
```

I do `node server.js` - it quietly waits. Then in a separate terminal I do `node client.js` and it blows up with
```
(node:55277) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'types' of undefined
    at MockttpClient.typeHasField (/Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:311:51)
    at MockttpClient.<anonymous> (/Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:118:23)
    at Generator.next (<anonymous>)
    at /Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:7:12)
    at MockttpClient._addRules (/Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:114:52)
    at MockttpClient.<anonymous> (/Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:109:25)
    at Generator.next (<anonymous>)
    at /Users/mvasin/playground/mockttp/node_modules/mockttp/dist/client/mockttp-client.js:11:71
(Use `node --trace-warnings ...` to show where the warning was created)
(node:55277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:55277) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I tried to replace `getRemote()` with `.getLocal()` in `client.js`, then it blows up with
```
(node:55628) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:55628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pimterry** [comment]
> AFAIK it's not the case for Cypress - the test code runs in the browser, but the browser API also has cy.exec and cy.task commands that allow to execute arbitrary code in the counterpart Node process.

Interesting! Ok, yes you have two options then: you can orchestrate everything within the `cy.{exec,task}` commands, or you can use `getStandalone()` from there first, and then orchestrate from browser code. Once the server is setup the API is the same either way.

There's a couple of issues in your example:

* You need to `await mockServer.start()` in client.js before adding rules. You've started a standalone server, but that's not the same as a mock server. The standalone server is a server that can be used to start mock servers (any number of them, but initially zero). You're right that error's not great there though, [now fixed]().

* You're making the request to port 8080, but your mock server isn't necessarily running on that port. You can either start it with a fixed port (`mockServer.start(8080)`) or use random ports to avoid conflicts and get the URL from the server (e.g. `mockServer.url` or `mockServer.urlFor("/mocked-path")`).

If you replace your `client.js` with this then it works, for example:

```js
const mockServer = require('mockttp').getRemote()
const superagent = require('superagent')

mockServer.start()
  .then(() => mockServer.get("/mocked-path").thenReply(200, "A mocked response"))
  .then(() => superagent.get(mockServer.urlFor("/mocked-path")))
  .then(response => console.log('response.text:', response.text))
```

**Comment by mvasin** [comment]
Thank you for the example, Tim, it works.

I'm still puzzled how the connection is established; how a client finds a server when no ports are specified.

Also, when I specify exact port `5555`...

server.js
```
require('mockttp').getStandalone().start(5555)
```

client.js
```
const mockServer = require('mockttp').getRemote()
const superagent = require('superagent')

mockServer.start(5555)
  .then(() => mockServer.get("/mocked-path").thenReply(200, "A mocked response"))
  .then(() => superagent.get(mockServer.urlFor("/mocked-path")))
  .then(response => console.log('response.text:', response.text))
```
...the client blows up with:
```
UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to standalone server at http://localhost:45456
```

Why `45456`?

**Comment by pimterry** [comment]
The standalone server and `getRemote()` both default to `localhost:45456`, which is how they connect to enable setup.

Starting a mockttp server is a two-stage process:

1. Set up Mockttp
  * For node tests that's just `mockServer = getLocal()`
  * For browser tests you need to start a standalone, and then connect to it from the browser with `mockServer = getRemote()`.
2. Start the mock server with `mockServer.start()`

In your example, you're trying to start a mock server without first successfully connecting to the standalone server. The port you pass to `mockServer.start()` is the port that will receive and handle requests from your production code, which is separate from the standalone port (which receives and handles requests to manage mock servers). Before calling `start()` you need to provide the latter to `getRemote()`, or it uses the default of 45456.

If you need to change the standalone port, you can override it by setting a port with `getStandalone().start(...)` (as you're doing) and then using it with `getRemote({ standaloneServerUrl: 'http://localhost:...' })`.

In practice though, you should be able to ignore all of this. The defaults work out of the box & totally automatically for most cases.

**Comment by mvasin** [comment]
It's getting way more clear - the communication between the "remote control" and the "mock server factory" as opposed to communication between the "end clients" and "mock servers" that the "mock server factory" produces became more apparent.

Maybe you will consider using those terms on main readme page? And a small diagram of the flow of data between those four pieces would be even better (maybe a couple of diagrams - for the case when the remote control and the mock server factory are in the same process and when they are not).

I think I'm on my way to integrate Cypress and Mockttp, thank you! Closing the issue for now. Will share here an example Mockttp + Cypress repo here if I will come up with one.

**Comment by pimterry** [comment]
Great! Let me know how it goes. I've definitely been meaning to get around to adding more docs & diagrams, I'll see what I can do.

**Comment by mvasin** [comment]
Hey Tim,

good news - I came up with an Cypress + Mockttp example repo: https://github.com/mvasin/cypress-mockttp
