### ISSUE TITLE
Update dependency fetch-ponyfill to latest version ti fix security warning

### ISSUE THREAD

**Issue by ibratoev** [httptoolkit/mockttp#49]
The current version of `fetch-ponyfill` depends on a version of `node-fetch` that has a know CVE: https://github.com/advisories/GHSA-w7rc-rwvf-8q5r

![image](https://user-images.githubusercontent.com/62861/114766308-e93d3c80-9d6e-11eb-841c-384b763a54cb.png)

**Comment by pimterry** [comment]
Hi @ibratoev, thanks for reporting this. I've now done that update and pushed a new release. Do feel free to open a PR for changes like this in future!
