### ISSUE TITLE
Failing npm audit via `subscriptions-transport-ws`

### ISSUE THREAD

**Issue by roberttaylor426** [httptoolkit/mockttp#50]
`subscriptions-transport-ws` is no longer maintained and is currently falling foul of an [npm advisory](https://github.com/apollographql/subscriptions-transport-ws/issues/875).

Is it possible to switch to [graphql-ws](https://github.com/enisdenjo/graphql-ws) instead? I'm not sure how much work this would entail.

**Comment by pimterry** [comment]
All done! Fixed in v2.0.1. Just using a fork of subscriptions-transport-ws for now, might move to graphql-ws in future, but this should fix this immediate issue.

**Comment by roberttaylor426** [comment]
Thank you! Really appreciate your work on this project :+1:
