### ISSUE TITLE
Unknown TLS error: invalid library

### ISSUE THREAD

**Issue by kkaminski-github** [httptoolkit/mockttp#59]
Hey!

I have a problem, that after starting https proxy i see pretty often this error:
```
Unknown TLS error: [Error] {
  library: 'invalid library (0)',
  function: 'OPENSSL_internal',
  reason: 'invalid library (0)',
  code: 'ERR_SSL_INVALID_LIBRARY_(0)'
}
```

Node v12.16.0

Https requests works as intended. What does this error means and what can I do to remove it ;)

**Comment by pimterry** [comment]
Honestly, I have no idea. This means that some TLS client is connecting to Mockttp's HTTPS proxy, and for some reason during the initial handshake where they set up the connection there's a low-level OpenSSL error. I've never seen that before though, and I'm not sure what could cause this.

Most likely cause is that something in your Node.js configuration or this HTTP client's TLS configuration is very wrong somewhere.

Are you using a custom build of Node.js, or any special TLS/OpenSSL configuration, or anything else like that?

It might be worth using [Wireshark](https://www.wireshark.org/) to capture the raw bytes of the TLS connection, and taking a look at that to find failing TLS handshakes and see if there are any clues there.
