### ISSUE TITLE
Question on how to run standalone from command-line

### ISSUE THREAD

**Issue by ccristobal-skillz** [httptoolkit/mockttp#70]
Hello again,

I have a question about how I could go about creating a mockttp standalone server through the command line that would always be listening.

What I am trying to accomplish is to have a server that is always running in one shell, that would pass through any requests that are not matching a rule. Then, I want to have tests that can configure the mock server to add/remove rules using code such that I can intercept and do the rewrites accordingly and reset to a default state when it finishes.

I read that I can do 
`Running mockttp -c [test command], to start the server before your tests, and automatically shut it down afterwards.`
but I don't want the server to shutdown.

Is this possible?

**Comment by pimterry** [comment]
Hi @ccristobal-skillz, thanks for your message.

This is pretty easy to do I think. You'll need to make a JS script containing:

```javascript
const mockttp = require('mockttp');
const standaloneServer = mockttp.getStandalone();
standaloneServer.start().then(() => {
  console.log('Standalone server started');
});
```

If you run this with `node that-script.js` then it will run a standalone server forever, until that process is closed.

This will _not_ run a mock server, so it won't actually mock any traffic yet. To do so, in your tests, you need to add:

```javascript
const mockttp = require('mockttp');
const mockServer = mockttp.getRemote();

mockServer.start().then(async () => {
  await mockServer.forUnmatchedRequest().thenPassThrough();

  // Add any other rules for your test here
});
```

It's not easily possible to run a persistent mock server that gets reconfigured by multiple clients as you're describing unfortunately (the UX is very confusing: what if you have two clients at once? What happens to callback rules when the client is disconnected?) but it is very possible to run a persistent standalone server and then quickly start & stop the mock server for every test.

To do that, you should:

* Call `mockServer.start()` and wait for the returned promise before each test
* Call `mockServer.forUnmatchedRequest().thenPassThrough()` before each test - this sets the default behaviour for unmocked traffic
* Add rules with calls like `mockServer.forX().thenY()` for each mock you need for the specific test in question
* In your code, you can send requests via the mock server using `mockServer.url`. If you'd prefer to run the server on the same fixed port every time, you can pass a port to `mockServer.start(port)` in the first step.
* Call `mockServer.stop()` at the end of each test (this will reset all rules)

Does that work for you?

**Comment by ccristobal-skillz** [comment]
Another way to rephrase my questions: is it possible to start up a standalone server that will by default, pass through all unmatched requests?

Then, have clients connect and configure rules and reset rules before disconnecting.

So in an idle state (no tests running), all unmatched requests pass through as if there is no proxy.
And during active state (tests running), the proxy will handle whatever rules are built through the tests.

**Comment by pimterry** [comment]
> Another way to rephrase my questions: is it possible to start up a standalone server that will by default, pass through all unmatched requests?

Not by default, no. All traffic is unhandled if no rules are set. Rules are only set while a client is connected to the standalone server. When the client disconnects the mock server shuts down and all its rules go away.

That said, it is possible to do this with some custom logic. To do so, you could include a client inside the same script that starts the standalone server, and expose your own API to control that somehow. That client would create a default mock server and set rules to proxy traffic, and from your tests you could talk to your custom API to start/stop that mock server remotely. Your tests would stop the default mock server, start their own mock server, and then restart the mock server when they're done.

You even be able to automate that final step - you can listen for `mock-server-started` and `mock-server-stopping` events on the standalone server to detect when a client is connects & disconnects, so you could automatically start the default mock server when the test mock server stops.

This isn't something that's built-in though, no, you'll need to script the logic for this yourself. In future I'd like to have a headless mock server mode that would support this, and I do think it's possible (contributions welcome!) but doing so in a sensible way with a nice UX is very difficult and it's not a priority right now.

**Comment by ccristobal-skillz** [comment]
Excellent! I think this is what I was looking for!

I couldn't get the event-based startup/shutdown to work because I was somehow getting into a loop of starting and stopping itself, but this worked well:

```const mockttp = require('mockttp');
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello World!');
});

app.get('/connect', (req, res) => {
  remoteServer.stop();
  res.send('Connection established');
});

app.get('/disconnect', (req, res) => {
  remoteServer.start(8000).then(() => {
    remoteServer.forUnmatchedRequest().thenPassThrough();
  });
  res.send('Connection disconnected');
});

app.listen(port, () => {
  console.log(`Listening at http://localhost:${port}`);
});

const standaloneServer = mockttp.getStandalone({
  debug: true,
  serverDefaults: {
    https: {
      keyPath: '../config/mockttp/ca.key',
      certPath: '../config/mockttp/ca.crt',
    },
  },
});
standaloneServer.start().then(() => {
  console.log('Standalone server started');
});

const remoteServer = mockttp.getRemote();
remoteServer.start(8000).then(() => {
  remoteServer.forUnmatchedRequest().thenPassThrough();
});
```

I would then make a GET request before and after tests to release the port I was using so I could connect with a remote server connection.

**Comment by pimterry** [comment]
Yes, that looks like correct to me! Sounds like everything's working for you now, so I'm going to close this, but feel free to reply here if you're still having trouble, or open a new issue for anything else that comes up.
