### ISSUE TITLE
Feature Request: Add ability to customize the order in which rules are matched

### ISSUE THREAD

**Issue by tw3** [httptoolkit/mockttp#73]
Right now in `MockttpServer.findMatchingRule()` rule matching seems to always progress from the top of the array to the bottom of the array.  The first rule always gets top priority for matching.

```
        const rulesMatches = rules.map((r) => ({ rule: r, match: r.matches(request) }));

        // Evaluate the matches one by one, and immediately use the first
        for (let { rule, match } of rulesMatches) {
            if (await match && rule.isComplete() === false) {
                // The first matching incomplete rule we find is the one we should use
                return rule;
            }
        }
```

I would like the ability to rotate the rule priority.

For example with these rules:

```
  await server.forGet('/users').thenJson(200, [ 'u1', u2' ]); // (A)
  await server.forPut('/users').thenJson(200, { message: 'User added' }); // (B)
  await server.forGet('/users').thenJson(200, [ 'u1', u2', 'u3' ]); // (C)
```

* The first request to `GET /users` would match rule (A) and return `['u1', 'u2']`
* Rule matching would then start on Rule (B) going forward
* A request to 'PUT /users' would match rule (B)
* Rule matching would then start on Rule (C) going forward
* The second request to `GET /users` would match rule (C) and return `['u1', 'u2', 'u3]` (as if the user was added)

Is this currently possible?

If not are there plans to allow this?

I realize the caller could rotate the rules in the array and continually call `setRequestRules()` after each match, but that is more expensive as there is the overhead of disposing the previous rules and constructing new `RequestRule` objects in that method.

If there is no solution planned for this then I can just fork the mockttp repo and change `findMatchingRule()` to use a custom iterator, e.g. a [rotating iterator](https://gist.github.com/tw3/b6354bae2d4170fc72022f741ea5bb24).

**Comment by pimterry** [comment]
Hi @tw3. This might already be possible, but it depends on the exact details.

Mockttp doesn't actually always run the first matching rule. Instead, it runs the first matching _incomplete_ rule. If you don't specify, a rule is complete as soon as it's handled a request once, unless it's the last matching rule (in which case it'll repeat forever). The precise logic is implemented [here](https://github.com/httptoolkit/mockttp/blob/80dac33f8d3899197843e4034a3d40f2569217f6/src/server/mockttp-server.ts#L536-L550) and [here](https://github.com/httptoolkit/mockttp/blob/80dac33f8d3899197843e4034a3d40f2569217f6/src/rules/requests/request-rule.ts#L81-L93)

Given that, I think your example should sort-of work already. The first GET request for /users should match A (which will then be complete) and then the second (and all subsequent) GET requests will match C. Meanwhile all PUT requests will always match B.

If you test that out, does that not work correctly for you? If it's doing something unexpected, can you share a full failing example I can run?

You can also control this more explicitly by using methods like `.once()`, `.twice()`, `.times(n)`, and `.always()` (see the [RequestRuleBuilder docs](https://httptoolkit.github.io/mockttp/classes/RequestRuleBuilder.html)) like so:

```js
await server.forGet('/users').twice().thenJson(200, [ 'u1', u2' ]);
await server.forGet('/users').always().thenJson(200, [ 'u1', u2', 'u3' ]);
```

In this case, the first line will match twice, and then the 2nd line will match forever.

Does that help?

That said, this isn't the same as fully rotating. If you want the matching to go back to rule A again after rule C has run (and then round again and again in future), that's not currently possible. To do that right now you would have to create a single `.thenCallback(...)` rule with your own logic to switch between the responses. Is that what you want, or is the above enough?

**Comment by tw3** [comment]
@pimterry you're right: the 2nd request for `GET /user` does use rule (C) and output the new user.  I'm sorry for making the wrong assumption, I should've actually tested this :D

I noticed that the 3rd, 4th, 5th request etc also continue to match (C) which seems reasonable.

Basically I am trying to match requests from the browser with requests from a HAR file.  This will help me replay a specific sequence of API responses to reproduce a bug, for example.  I wrote some code to intercept, match, and replay traffic from a HAR file,  and it works well, but the code is embedded in the browser.  I am looking to move that functionality to a proxy using your awesome library so it can be separate from the frontend code.  The code I wrote uses a rotating iterator, but I think your complete/incomplete matcher may be better.

Your matcher always starts from rule 0 each time, right?  If so, supposing there are 200 rules and the first 150 are matched/complete, it will still loop through the matched rules before considering unmatched rules, right?  If so maybe that's where the rotating iterator would match faster b/c it would start on an unmatched rule.  But of course network requests don't always follow the same sequence each time, so that's where my rotating iterator could possibly return the wrong response while your matcher wouldn't.  I guess maybe it depends on the scenario.

Part of me wonders if it makes sense to abstract the the rule-matching behavior to a different class that could be customized using the strategy pattern.  The default strategy could the current one in `findMatchingRule()`.  Another strategy could be a combination of our approaches: mark complete/incomplete but start at the first un-matched rule and rotate/cycle around.  Another strategy could be to require an exact sequence of requests, and not re-match at all.  Etc.  I realize this could be overkill, or go against your design approach for the matcher.

Anyhow, I will try to make use of the built-in matcher, its a smart approach.  And if that doesn't work I can experiment with a customized-strategy design and see if that helps me.

Thanks for the quick and informative response!

**Comment by pimterry** [comment]
Ok, thanks for the context, very interesting! To be clear: given the existing behaviour, the only reason you might be interested in rule rotation is for rule matching performance? Is that right, or is there some other benefit?

If it is just for performance, I'd encourage you to really benchmark the impact of this in your code. For most usage of Mockttp, IO time on the network dwarfs CPU time (by many orders of magnitude) so this kind of performance is very rarely meaningful. If you are finding that rule matching is a significant factor for you though, I'd love to see a repro and benchmarks, I'm definitely interested in investigating any reproducible performance problems.

Right now, Mockttp isn't significantly optimized for CPU performance anywhere, since it's rarely used in environments where that matters (it's not designed to replace NGINX as the front-end reverse proxy for your entire production website, for example). If there are concrete performance issues, there's probably lots of scope for improvements there already available, with no need to change the resulting behaviour at all.

I'm open to it if it's really necessary, but otherwise I'm cautious about making rule matching configurable like this, because it becomes _very_ easy to create confusing behaviour and get the 'incorrect' response for a given request. It would be better to avoid it if possible I think.

**Comment by tw3** [comment]
Yeah the main concern would be performance with a large number of rules.  But as you mentioned I should benchmark that before raising it as something to prioritize.

Thanks!
