### ISSUE TITLE
How to create HTTPS-only server?

### ISSUE THREAD

**Issue by Kaciras** [httptoolkit/mockttp#86]
The server created by `getLocal({ https: { ... } })` accepts both HTTP and HTTPS connections, is there any way to reject requests without TLS?

**Comment by pimterry** [comment]
Hi @Kaciras. This isn't supported right now. In general it would be quite complicated to refuse the TLS connection entirely up front in the current model, but it could certainly be possible to reject all requests or forcibly close the connection after it opens.

To do that you'd want to add a rule matching all plain HTTP traffic and rejecting it, either with an error status response, or just outright closing the connection, up to you.

Right now there's no built-in support for matching the requests like this, but it would be easy to add it. You'd need to create a `ProtocolMatcher` class which takes a protocol (http/https) and checks it against the request URL, and then a small `.withProtocol(protocol)` helper method. As an example, for hostname matching the matcher is [here](https://github.com/httptoolkit/mockttp/blob/c56ad44bcfc29f25a3358abc4c7f24422d05f484/src/rules/matchers.ts#L104-L130) and the helper method is [here](https://github.com/httptoolkit/mockttp/blob/c56ad44bcfc29f25a3358abc4c7f24422d05f484/src/rules/base-rule-builder.ts#L97-L105). Would you like to open a PR?

Once that's added, the code to do this could look like:

```javascript
mockServer.forAnyRequest().withProtocol('http').always().thenCloseConnection();
```

Adding this as the first rule in your server would kill all plain HTTP connections.

**Comment by shirshak55** [comment]
@pimterry it gives warning Property 'withProtocol' does not exist on type 'RequestRuleBuilder'

**Comment by Kaciras** [comment]
@pimterry I found a confusion that in proxied requests, the connection and the proxy destination can have different protocols.

for example:

```javascript
import { fetch, ProxyAgent } from "undici";
import { getLocal } from "mockttp";

const server = getLocal();
await server.start();
await server.forGet("https://example.com")
  .matching(request => {
    console.log("Request URL is "+ request.url);
    return request.protocol === "https";
  })
  .thenReply(200, "DATA");

const proxyURL = "http://[::1]:8000";
const distURL = "https://example.com";

const dispatcher = new ProxyAgent({ uri: proxyURL });
console.log((await fetch(distURL, { dispatcher })).status);
```

The `request.protocol` is `https` in the `matching` callback, but the server is not configure for TLS. 

Maybe need to add another protocol matcher for this case.

**Comment by pimterry** [comment]
That's OK, I think this is expected. All matching applies to the final request data, not to the details of how it's proxied. That's the same as hostname matching: it matches the target server address, not the address you used to reach the proxy.

I'm open to rules matching the proxy data, if that's something you'd find useful, but I haven't ever seen any use cases where people want to do that.
