### ISSUE TITLE
Bug: onRequest body maximum size is 67.66 kb?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/mockttp#92]
After a lot of debugging, I finally found the culprit. It seems I can't respond to sizes greater than 67.66 kb. 

To reproduce
```js
import mockttp, { getLocal } from "mockttp";

import fsp from "fs/promises";
import fs from "fs";
import path from "path";
import delay from "delay";
import highwayhash from "highwayhash";

let key = Buffer.from("12345678912345678912345678912345");

async function main() {
  let httpsConfig;

  if (fs.existsSync("./certs/key.pem") && fs.existsSync("./certs/cert.pem")) {
    httpsConfig = {
      key: (await fsp.readFile("./certs/key.pem")).toString(),
      cert: (await fsp.readFile("./certs/cert.pem")).toString(),
    };
  } else {
    httpsConfig = await mockttp.generateCACertificate();

    await fsp.writeFile("./certs/key.pem", httpsConfig.key);
    await fsp.writeFile("./certs/cert.pem", httpsConfig.cert);
  }
  const server = getLocal({
    https: httpsConfig,
  });

  // server.forAnyRequest().withProtocol('http').always().thenCloseConnection();
  let dataStore = {};

  if (!fs.existsSync("./cache")) {
    await fsp.mkdir("./cache");
  }

  if (fs.existsSync("./cache/data_index.json")) {
    dataStore = JSON.parse(
      (await fsp.readFile("./cache/data_index.json")).toString()
    );
  }

  let extensions = [
    ".png",
    ".gif",
    ".ico",
    "CGI_Logo",
    ".jpg",
    ".css",
    "themes/ui-lightness",
    ".js",
  ];

  let ids_to_link = {};
  server.on("request", async (req) => {
    ids_to_link[req.id] = req.url;
  });

  let banned_links = new Set();
  banned_links.add("http://update.googleapis.com/service/update2/json");

  server.forAnyRequest().thenPassThrough({
    beforeRequest: async (req) => {
      if (
        banned_links.has(req.url) ||
        req.url.includes("update.googleapis.com") ||
        req.url.includes("edgedl.me.gvt1.com") ||
        req.url.includes("ga.js")
      ) {
        return {
          response: {
            status: 400,
          },
        };
      }

      if (extensions.some((v) => req.url.includes(v))) {
        let hash = highwayhash.asString(key, Buffer.from(req.url));

        if (hash in dataStore) {
          if (
            fs.existsSync(dataStore[hash].body_path) &&
            fs.existsSync(dataStore[hash].headers_path)
          ) {
            let body = await fsp.readFile(dataStore[hash].body_path);

            if (req.url.includes("jquery-1.4.4.min.js"))
              console.log(body.toString());
            return {
              response: {
                status: 200,
                body: body,
                headers: JSON.parse(
                  (await fsp.readFile(dataStore[hash].headers_path)).toString()
                ),
              },
            };
          }
        }
      }
      return undefined;
    },

    beforeResponse: async (res) => {
      if (res.id in ids_to_link) {
        let link = ids_to_link[res.id];
        let hash = highwayhash.asString(key, Buffer.from(link));
        let pth = path.join(`./cache/${hash}`);
        let hpth = path.join(`./cache/${hash}_headers`);
        if (
          extensions.some((v) => link.includes(v)) ||
          link.includes("static")
        ) {
          let buffer = await res.body.getDecodedBuffer();
          await fsp.writeFile(pth, buffer);
          await fsp.writeFile(hpth, JSON.stringify(res.headers));
          dataStore[hash] = {
            body_path: pth,
            headers_path: hpth,
          };
        }
      }

      return undefined;
    },

    trustAdditionalCAs: [
      { certPath: "/home/quantum/.config/httptoolkit/ca.pem" },
    ],

    proxyConfig: {
      proxyUrl: "http://127.0.0.1:8000",
    },
  });

  // server.enableDebug();
  await server.start(1055);
  saveCacheForFuture(dataStore);
  console.log(`Server running on port ${server.port}`);
}

async function saveCacheForFuture(dataStore: any) {
  while (true) {
    try {
      await fsp.writeFile("./cache/data_index.json", JSON.stringify(dataStore));
    } catch (e) {
      console.log("Err on save cache index", e);
    } finally {
      await delay(5000);
    }
  }
}

main().catch((e) => console.log("Err from main", e));

```

After this, I connected firefox and loaded jquery. Jquery was loaded properly the first time due to upstream proxy. But as the file was cached on the second iteration it only showed content up to 67.66 kb. Other data were lost, and only few part of jquery was sent to firefox browser.

**Comment by pimterry** [comment]
Where exactly is this data getting truncated?

Is the data returned by `getDecodedBuffer` too short?

Is the data in the cache file correct?

Is the value truncated at the point where you return it from `beforeRequest`?

If you can narrow down the exact point where this goes wrong then it should be easy to find what's causing this limitation. I'm fairly sure this isn't a general limitation in Mockttp (HTTP Toolkit handles larger bodies like this no problem AFAIK) so there must be something else going on somewhere.

**Comment by shirshak55** [comment]
@pimterry getDecodedBuffer seems to save data correctly. The problem seem to happen in this line?
```
return {
              response: {
                status: 200,
                body: body,
                headers: JSON.parse(
                  (await fsp.readFile(dataStore[hash].headers_path)).toString()
                ),
              },
            };
```
To be more specific it seems to happen here: 

` body: body,`
 
 

it seems the body can't be greater than 67.66 kb. 

The cache file looks healthy, and   console.log(body.toString()); gives correct response too.

**Comment by shirshak55** [comment]
Here is the screenshot to illustrate this problem.

![image](https://user-images.githubusercontent.com/8097377/170767511-eac3e137-21ca-4a42-89f7-be3bfb61ffde.png)

**Comment by shirshak55** [comment]
Screenshot here. (I have scrolled both to bottom)

![image](https://user-images.githubusercontent.com/8097377/170767746-9354a009-a68a-4fd6-9952-293522891456.png)

**Comment by pimterry** [comment]
I suspect the headers are the problem here. The headers match the original encoded body, and you're returning a decoded body.

What probably happens is that the response is encoded (i.e. compressed, so the body size when it was sent is shorter than its real size). The `content-encoding` header will tell you what encoding, and the `content-length` header will have been set to the encoded size. You're returning decoded data in the `body` field in `beforeRequest`, which Mockttp will encode for you automatically, but when it does that the size won't match exactly, and any data longer than the content-length header from the original response will be lost. Does that make sense?

You can check this by looking at the content-length in the headers. I bet it's a number like 67660. If you remove that header this might work immediately (although not sending any content-length at all has a performance hit, since it means keep-alive doesn't work).

Alternatively, you could store the encoded data instead of the decoded data (use `.buffer` instead of `.getDecodedBuffer`) and return the data in `beforeRequest` with `rawBody` instead of `body` to stop Mockttp from re-encoding the data for you. In that case you'll be returning the original body, which should match the original headers correctly.

**Comment by shirshak55** [comment]
@pimterry good points. No wonder why they say caching is the most difficult problem in CS :) Thanks, and please forgive me for my ignorance :).
