### ISSUE TITLE
TLS client error: cert-rejected

### ISSUE THREAD

**Issue by Lautenschlager-id** [httptoolkit/mockttp#94]
Hello!

Had been using mockttp for quite a while now, but now I can fix this random issue that started this week in my new device...

My current code looks simple like this:
```JS
const { getLocal, generateCACertificate  } = require("mockttp");
server = getLocal({
            https: await generateCACertificate(),
            debug: true
}):
// adb gets executed to setup a proxy at 10.0.0.137:6969 so I can listen my android traffic
await server.anyRequest().thenPassThrough();
await server.start(6969);
```

That used to work very well, but now checking the traffic through the debug option, it seems that no request is making it. I only receive the following:
```
Proxying HTTP/1 CONNECT to something.com.br:666
Generating certificate for something.com.br
TLS client error: {"failureCause":"cert-rejected","hostname":"something.com.br","remoteIpAddress":"::ffff:10.0.0.167","remotePort":12345,"tags":[],"timingEvents":{"startTime":1654914147025,"connectTimestamp":9736.930000007153,"tunnelTimestamp":9739.19059997797,"failureTimestamp":9764.308200001717}}
```

I have tried in two other devices and the same issue persists :/ Maybe I'm failing at the CA part?

**Comment by Lautenschlager-id** [comment]
It turns out that my CA cert had expired and I though I had reinstalled it, but I think they went missing when I updated my android. Retried the install and it's working now \o/

**Comment by pimterry** [comment]
Ah, that'll do it! Glad you got this sorted @Lautenschlager-id :+1:
